version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
          - my_network
    ports:
      - "${DATABASE_PORT}:5432"
  app:
    build: .
    ports:
      - "3000:3000"  # Map the port from the container to the host (adjust if your app uses a different port)
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
          - my_network
    

volumes:
  postgres_data:

networks:
    my_network:
      driver: bridge